In [2]:
# Dependences
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Experiments
del configs[:]
from model import run
# from model.parts.utils import *

df = run.run()
#rdf = run.postprocessing(df)
#rdf = df # debugging substeps#

                  ___________    ____
  ________ __ ___/ / ____/   |  / __ \
 / ___/ __` / __  / /   / /| | / / / /
/ /__/ /_/ / /_/ / /___/ ___ |/ /_/ /
\___/\__,_/\__,_/\____/_/  |_/_____/
by cadCAD

Execution Mode: local_proc
Configuration Count: 1
Dimensions of the first simulation: (Timesteps, Params, Runs, Vars) = (400, 4, 1, 2)
Execution Method: local_simulations
SimIDs   : [0]
SubsetIDs: [0]
Ns       : [0]
ExpIDs   : [0]
Execution Mode: single_threaded
Total execution time: 0.03s

In [4]:
df

     population     food  simulation  subset  run  substep  timestep
0            50  1000.00           0       0    1        0         0
1            60  1009.50           0       0    1        1         1
2            70  1018.90           0       0    1        1         2
3            80  1028.20           0       0    1        1         3
4            90  1037.40           0       0    1        1         4
..          ...      ...         ...     ...  ...      ...       ...
396        1102   902.16           0       0    1        1       396
397        1101   901.14           0       0    1        1       397
398        1100   900.13           0       0    1        1       398
399        1099   899.13           0       0    1        1       399
400        1098   898.14           0       0    1        1       400

[401 rows x 7 columns]